const Api = [
  {
    "result": {
      "cool_down": {
        "elements": [
          {
            "body_part": "",
            "break_duration": 0,
            "category": "lower_body",
            "comment": "hello",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "aea3ced0d2fee870",
            "entry_id": "4d07c5b852f9a03c",
            "equipment_needed": "",
            "group_id": "_0.3352939879291341",
            "group_type": "set",
            "media_link": "",
            "name": "Cooldown simple exercise",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 3,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "7799439b15597ddf",
            "entry_id": "d5e0f3d96fefaadd",
            "equipment_needed": "",
            "group_id": "_0.29387293748981813",
            "group_type": "super_set",
            "media_link": "",
            "name": "Cooldown Superset 1 Exercise 1",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "7180cf643c632b26",
            "entry_id": "b7576b09e5f4d33e",
            "equipment_needed": "",
            "group_id": "_0.29387293748981813",
            "group_type": "super_set",
            "media_link": "",
            "name": "Cooldown Superset 1 Exercise 2",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "376a580a89ff5d3c",
            "entry_id": "e501e960e66f26b4",
            "equipment_needed": "",
            "group_id": "_0.9529235274151375",
            "group_type": "super_set",
            "media_link": "",
            "name": "Cooldown Superset 2 Exercise 1",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "ff57651c050e44c7",
            "entry_id": "9bfcb731b4313d60",
            "equipment_needed": "",
            "group_id": "_0.9529235274151375",
            "group_type": "super_set",
            "media_link": "",
            "name": "Cooldown Superset 2 Exercise 2",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          }
        ],
        "entry_id": "d4d0d9fddcec8ad3"
      },
      "duration": 60,
      "entry_id": "0f6f068de75fd12e",
      "equipment_needed": "",
      "focus_on": "Building triceps.",
      "order": 0,
      "thumbnail": "uploads/fd9a6f6487836043/0DwIQmazMAGa7xE8FdLjtQ/thumbnail_1200x800-1-1024x683.jpeg",
      "warm_up": {
        "elements": [
          {
            "body_part": "",
            "break_duration": 120,
            "category": "upper_push",
            "comment": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "db_entry_id": null,
            "duration": 1800,
            "element_id": "1778598f67d82932",
            "entry_id": "0151b3dfc220a2ad",
            "equipment_needed": "Barbell",
            "group_id": "_0.5456374515547879",
            "group_type": "tri_set",
            "media_link": "https://youtu.be/Im4bjPabf2c",
            "name": "Barbell Push Jerk",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 3,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 120,
            "category": "upper_pull",
            "comment": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "5b7c2129a8374169",
            "entry_id": "b6148e73f9b015e0",
            "equipment_needed": "Barbell",
            "group_id": "_0.5456374515547879",
            "group_type": "tri_set",
            "media_link": "https://youtu.be/M4bigTXfpkA",
            "name": "Barbell Deadlift (conventional)",
            "order": 0,
            "repeats": 8,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 3,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 120,
            "category": "lower_body",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "988902741ff9fc5f",
            "entry_id": "19dc5bb2c710f6d5",
            "equipment_needed": "Barbell",
            "group_id": "_0.5456374515547879",
            "group_type": "tri_set",
            "media_link": "https://youtu.be/vtp5FRMV5u8",
            "name": "Barbell Cossack Squat",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 3,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 30,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 180,
            "element_id": "6bf5362f6658721a",
            "entry_id": "47a9a8ff829a88ac",
            "equipment_needed": "None",
            "group_id": "_0.7189822715840213",
            "group_type": "super_set",
            "media_link": "https://youtu.be/25_3JZDmf5A",
            "name": "High Plank",
            "order": 0,
            "repeats": 1,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 30,
            "category": "upper_pull",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "b07e46806c9054b7",
            "entry_id": "d2ec4f9dcfdfd1c9",
            "equipment_needed": "None",
            "group_id": "_0.7189822715840213",
            "group_type": "super_set",
            "media_link": "https://youtu.be/TYbkz2B5l9U",
            "name": "Leg Lowers",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "upper_pull",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "ccd33c3b68bed10e",
            "entry_id": "2001a9dc855aa074",
            "equipment_needed": "",
            "group_id": "_0.13425864358969775",
            "group_type": "giant_set",
            "media_link": "",
            "name": "Exercise 1",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "154f4c4b6f4464f0",
            "entry_id": "a5c5a8383324e966",
            "equipment_needed": "",
            "group_id": "_0.13425864358969775",
            "group_type": "giant_set",
            "media_link": "",
            "name": "Exercise 2",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "e5fcfda97274b5bf",
            "entry_id": "efb6f9abab6f3754",
            "equipment_needed": "",
            "group_id": "_0.13425864358969775",
            "group_type": "giant_set",
            "media_link": "",
            "name": "Exercise 3",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 0,
            "element_id": "6515c9f60c20a0df",
            "entry_id": "ddbaaeb8f27911dd",
            "equipment_needed": "",
            "group_id": "_0.13425864358969775",
            "group_type": "giant_set",
            "media_link": "",
            "name": "Exercise 4",
            "order": 0,
            "repeats": 0,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 0
          }
        ],
        "entry_id": "60408447cb80d001"
      },
      "workout": {
        "elements": [
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 600,
            "element_id": "6866b562d73090e4",
            "entry_id": "2d6e4b3260cf039c",
            "equipment_needed": "",
            "group_id": "_0.23801465619513618",
            "group_type": "set",
            "media_link": "",
            "name": "Workout Exercise 1",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 1,
            "weight": 40
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 600,
            "element_id": "ea1c06d9399d4275",
            "entry_id": "abf35881035e86e0",
            "equipment_needed": "",
            "group_id": "_0.6269723358985491",
            "group_type": "set",
            "media_link": "",
            "name": "Workout Exercise 2",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 4,
            "weight": 40
          },
          {
            "body_part": "",
            "break_duration": 0,
            "category": "other",
            "comment": "",
            "db_entry_id": null,
            "duration": 600,
            "element_id": "d33171092be9a7fe",
            "entry_id": "62d464c47a75ad73",
            "equipment_needed": "",
            "group_id": "_0.5908309536764327",
            "group_type": "set",
            "media_link": "",
            "name": "Workout Exercise 3",
            "order": 0,
            "repeats": 10,
            "rich_text": "",
            "rich_text_selected": false,
            "sets_number": 2,
            "weight": 40
          }
        ],
        "entry_id": "641232d98361ec4f"
      }
    },
    "status": 200
  }
]

export default Api;